### ISSUE TITLE
Nodes doesn't work in latest node-red

### ISSUE THREAD

**Issue by HaTWare** [node-red-contrib/node-red-contrib-bsb-lan#222]
The nodes return the error (in debug view) : 

'"error TypeError: axios_1.default is not a function"'. 

Propably need to adjust to the lates axios version.

**Comment by henrythasler** [comment]
Same here with node-red 3.0.2

**Comment by konne** [comment]
@henrythasler @HaTWare it should work now. Please check, if you still have an issue, reopne the ticket
